repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v21.1.0
  hooks:
  - id: clang-format
    files: '.*\.(hpp|cpp|h)'
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.7.7.24
  hooks:
    - id: actionlint
      additional_dependencies: [shellcheck-py]

  
